kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
rules:
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs: ["get", "list", "watch"]
