{{- if .Values.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "labels" . | nindent 4 }}
{{- if .Values.istioLabels }}
{{ toYaml .Values.istioLabels | indent 4 }}
{{- end }}
spec:
  host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
{{- if .Values.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- toYaml .Values.destinationRule.trafficPolicy | nindent 4 }}
{{- end }}
{{- if .Values.destinationRule.subsets }}
  subsets:
    {{- toYaml .Values.destinationRule.subsets | nindent 4 }}
{{- end }}
{{- end }}
