apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "istio-redirector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Release.Name }}
