apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  maxUnavailable: {{ .Values.pdb }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
