{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "labels" . | nindent 4 }}
spec:
  jobLabel: app
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "istio-redirector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Release.Name }}
{{- end }}
