apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "labels" . | nindent 4 }}
  annotations:
{{- with .Values.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "istio-redirector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}

