apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-redirector-test-vs
  namespace: istio-system
  labels:
    app: istio-redirector
spec:
  exportTo:
    - "."
  gateways:
    - istio-system/istio-ingressgateway
  hosts:
    - example.com
  http:
  - match:
    - uri:
        exact: /a
    redirect:
      uri: /
      redirectCode: 301
