server:
  URL: "localhost:8080"
  allowedOrigins:
    - "*"

istio:
  gateways:
    - istio-system/istio-ingressgateway
  
frontendConfig:
  enableGitHub: false
  availableNamespace:
    - default
  availableCluster:
    - prod
  availableDestinationSvc:
    - my_svc.svc

github:
  token: my_secret_token # The GitHub Token used to authenticate
  email: "test@example.com" # The email used for the commits
  owner: example # The GitHub username hosting your GitOps repository
  repo: "istio-redirector" # The name of your GitOps repository
  baseRef: "master" # The branch name used for the checkout
  newBranchPrefix: "new-redirections" # The prefix used the Pull Request name
