server:
  URL: "localhost:8080"
  allowedOrigins:
    - "*"

istio:
  destinationRule: "example.istio-system.svc.cluster.local" # The Destination Rule used for 4xx
  defaultDestinationHost: "example.istio-system.svc.cluster.local" # The Service used if there was no other match
  fallbackMatchingRegex: "/test($|/.*)" # The regex used to catch all other requests
  gateways:
    - istio-system/istio-ingressgateway
  exportTo:
    - "." # "." works if Virtual Services are created in the same namespace than your Gateways, usually istio-system

frontendConfig:
  availableNamespace:
    - default
  availableCluster:
    - prod

github:
  token: my_secret_token # The GitHub Token used to authenticate
  email: "test@example.com" # The email used for the commits
  owner: example # The GitHub username hosting your GitOps repository
  repo: "istio-redirector" # The name of your GitOps repository
  baseRef: "master" # The branch name used for the checkout
  newBranchPrefix: "new-redirections" # The prefix used the Pull Request name
